apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # want to reach out to letsencrypt - production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory # what server to go to
    email: 'greese@seeddevs.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {} # want to use typical http process of obtaining certificate, there are others